# Generated by Django 2.1.5 on 2019-02-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('aux_identification', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('registered', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('interests', models.ManyToManyField(to='interests.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(help_text='in euros')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interests.Product')),
                ('editor', models.CharField(max_length=50)),
                ('weight', models.PositiveIntegerField()),
            ],
            bases=('interests.product',),
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interests.Product')),
                ('release_date', models.DateField()),
                ('volume', models.PositiveIntegerField()),
                ('historical_maximum', models.PositiveIntegerField()),
                ('historical_minimum', models.PositiveIntegerField()),
                ('weekly_price', models.PositiveIntegerField()),
                ('monthly_price', models.PositiveIntegerField()),
            ],
            bases=('interests.product',),
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interests.Product')),
                ('editor', models.CharField(max_length=50)),
                ('download_link', models.URLField()),
            ],
            bases=('interests.product',),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interests.Product')),
                ('_class', models.CharField(choices=[('tourist', 'tourist'), ('executive', 'executive'), ('first_class', 'first_class')], max_length=5)),
                ('departure', models.DateTimeField()),
                ('landing', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_city', to='interests.City')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_city', to='interests.City')),
            ],
            bases=('interests.product',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interests.Product')),
                ('rating', models.CharField(choices=[('disgusting', '**'), ('fair', '***'), ('good', '****'), ('superb', '*****')], max_length=5)),
                ('acommodation_duration', models.PositiveIntegerField()),
                ('acommodation_start', models.DateTimeField()),
                ('acommodation_end', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interests.City')),
            ],
            bases=('interests.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='interests.Category'),
        ),
        migrations.AddField(
            model_name='credit',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='interests.Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(to='interests.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='interests.Customer'),
        ),
    ]
